name: .NET CI

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main # Trigger on pull requests to the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.x" # Replace with your .NET version (e.g., 6.x, 7.x)

        # Navigate to the subdirectory
      - name: Change to ElevatorSimulator directory
        run: cd ElevatorSimulator
        shell: bash

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build the project
      - name: Build
        run: dotnet build --configuration Release --no-restore

      # Run tests
      - name: Test
        run: dotnet test --no-build --verbosity normal
